### ISSUE TITLE
Sorting question

### ISSUE THREAD

**Issue by IanaKhitsko** [Gedion22/Design_technology_lab1#4]
https://github.com/Gedion22/Design_technology_lab1/blob/8164dee4fa2a92ebb9ae8a8a00e747bb8d91420e/Grid.ts#L155

I'm not familiar with TS, so please explain how it works - the function returns bool or int {-1,0,1} ?

**Comment by Aqkuma** [comment]
> https://github.com/Gedion22/Design_technology_lab1/blob/8164dee4fa2a92ebb9ae8a8a00e747bb8d91420e/Grid.ts#L155
> 
> I'm not familiar with TS, so please explain how it works - the function returns bool or int {-1,0,1} ?
int {-1,0,1}

**Comment by Aqkuma** [comment]
the function returns int {-1,0,1}
