### ISSUE TITLE
Variables and functions

### ISSUE THREAD

**Issue by Vlladdd** [Gedion22/Design_technology_lab1#8]
https://github.com/Gedion22/Design_technology_lab1/blob/e96601535ffcb23a1d928fd6c568192c0819b277/City.ts#L4-L9

Consider making variables and functions private by default unless they called in other classes. Or you can make getters and setters.

**Comment by Aqkuma** [comment]
In JS there are no private properties of classes as such, because classes in JS are essentially simple objects, therefore getters and setters are just extra code
